@hostname = localhost 
@port = 5101 
@host = https://{{hostname}}:{{port}} 
@contentType = application/json

###
GET {{host}}/api/Users

###
GET {{host}}/api/Users/3

###
DELETE {{host}}/api/Users/0

###
POST {{host}}/api/Users 
Content-Type: {{contentType}}

{
    "Id":"32",
    "FirstName":"Luis", 
    "LastName":"fsdfdsf"
}

###
PUT {{host}}/api/Users/1
Content-Type: {{contentType}}

{
    "Id":1,
    "FirstName":"Luis",
    "LastName": "Garcia"
}
