# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - TechGlue-EWU-CSCD379-2021-Spring(Production), Build and deploy DotnetCore app

on:
  push:
    branches: [ Assignment-* ]
  pull_request:
    branches: [ Assignment-* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: npm install
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: install
      
    - name: npm build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm run build:prod
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: dotnet publish
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binSecretSanta

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: TechGlue-EWU-CSCD379-2021-Spring
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C041DA63ACC3477381F0839F2D327EBF }}
        package: ${{env.DOTNET_ROOT}}/binSecretSanta

