# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure Deployment

on:
  push:
    branches: [ Assignment-* ]
  pull_request:
    branches: [ Assignment-* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    ###Web###
    - name: npm install
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm install
      
    - name: npm build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm run build:prod
      
    - name: Restore dependencies Web 
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet restore

    - name: Build Web 
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet build --no-restore --configuration Release
    ###Api###  
    - name: Restore dependencies API
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet restore

    - name: Build API 
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet build --no-restore --configuration Release
    ###Publishing Api and Web###
    - name: dotnet publish Web
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binSecretSanta

    - name: dotnet publish API
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binSecretSantaApi

    ###Running API and Web###
    - name: Run Azure API App 
      uses: azure/webapps-deploy@v2
      with:
        app-name: API-EWU-CSCD379-2021-Spring
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_241327426D6F4F279D4FC01DCAB4A092 }}
        package: ${{env.DOTNET_ROOT}}/binSecretSantaApi

    - name: Run Azure webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: TechGlue-EWU-CSCD379-2021-Spring
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C041DA63ACC3477381F0839F2D327EBF }}
        package: ${{env.DOTNET_ROOT}}/binSecretSanta

