name: .NET

on:
  push:
    branches: [ Assignment-* ]
  pull_request:
    branches: [ Assignment-* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Get Directory
      run: pwd
      
    - name: npm install
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm install
      
    - name: npm build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: npm run build:prod
      
    - name: Restore dependencies
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet restore

    - name: Build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet build --no-restore
      
    ###API##
    - name: Test
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet test --no-build --verbosity normal
      
    - name: Restore dependencies
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet restore

    - name: Build
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet test --no-build --verbosity normal


